# ─────────────────────────────────────────────────────────────────
# rules.mk — keyboard level
# Generated by QMK/Vial Wizard v5.6 on 2026-09-05
# ─────────────────────────────────────────────────────────────────
#
# IMPORTANT: Do NOT add VIAL_ENABLE or VIA_ENABLE here.
# Per official Vial docs (https://get.vial.today/docs/porting-to-vial.html),
# those flags belong only in keymaps/vial/rules.mk.
# Placing them here breaks compatibility with standard QMK builds.
#
# All hardware config (MCU, bootloader, pins) lives in keyboard.json.
#
# LTO (Link-Time Optimization) and NKRO are set here because vial-qmk's
# keyboard.json schema does not support these as features keys.
LTO_ENABLE = yes
NKRO_ENABLE = yes
